###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Dict, List, Optional, TypeVar, Union, TypedDict, Type, Literal, cast
from typing_extensions import NotRequired
import pprint

import baml_py
from pydantic import BaseModel, ValidationError, create_model

from . import partial_types, types
from .types import Checked, Check
from .type_builder import TypeBuilder
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME

OutputType = TypeVar('OutputType')

# Define the TypedDict with optional parameters having default values
class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]

class BamlSyncClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __stream_client: "BamlStreamClient"

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__stream_client = BamlStreamClient(self.__runtime, self.__ctx_manager)

    @property
    def stream(self):
      return self.__stream_client

    
    def ExtractAgentParticipations(
        self,
        scene_text: str,story_context: Optional[str],events: List[types.Event],agents: List[str],
        baml_options: BamlCallOptions = {},
    ) -> List[types.AgentParticipation]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractAgentParticipations",
        {
          "scene_text": scene_text,"story_context": story_context,"events": events,"agents": agents,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.AgentParticipation], raw.cast_to(types, types))
    
    def ExtractAgents(
        self,
        scene_text: str,story_context: Optional[str],known_agents: List[types.Agent],agent_name_to_uuid_mapping: Dict[str, str],
        baml_options: BamlCallOptions = {},
    ) -> List[types.Agent]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractAgents",
        {
          "scene_text": scene_text,"story_context": story_context,"known_agents": known_agents,"agent_name_to_uuid_mapping": agent_name_to_uuid_mapping,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.Agent], raw.cast_to(types, types))
    
    def ExtractAllWikiData(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.WikiData:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractAllWikiData",
        {
          "text": text,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.WikiData, raw.cast_to(types, types))
    
    def ExtractCastCrew(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CastCrew:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractCastCrew",
        {
          "text": text,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.CastCrew, raw.cast_to(types, types))
    
    def ExtractContinuity(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Continuity:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractContinuity",
        {
          "text": text,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.Continuity, raw.cast_to(types, types))
    
    def ExtractEntities(
        self,
        scene_text: str,story_context: Optional[str],
        baml_options: BamlCallOptions = {},
    ) -> types.OntoMediaEntities:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractEntities",
        {
          "scene_text": scene_text,"story_context": story_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.OntoMediaEntities, raw.cast_to(types, types))
    
    def ExtractEpisodePlot(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> List[types.EpisodePlot]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractEpisodePlot",
        {
          "text": text,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.EpisodePlot], raw.cast_to(types, types))
    
    def ExtractEvents(
        self,
        scene_text: str,story_context: Optional[str],scene_number: int,known_agents: List[str],known_objects: List[str],
        baml_options: BamlCallOptions = {},
    ) -> List[types.Event]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractEvents",
        {
          "scene_text": scene_text,"story_context": story_context,"scene_number": scene_number,"known_agents": known_agents,"known_objects": known_objects,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.Event], raw.cast_to(types, types))
    
    def ExtractHomeMedia(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.HomeRelease:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractHomeMedia",
        {
          "text": text,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.HomeRelease, raw.cast_to(types, types))
    
    def ExtractLocations(
        self,
        scene_text: str,story_context: Optional[str],
        baml_options: BamlCallOptions = {},
    ) -> List[types.Location]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractLocations",
        {
          "scene_text": scene_text,"story_context": story_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.Location], raw.cast_to(types, types))
    
    def ExtractObjectInvolvements(
        self,
        scene_text: str,story_context: Optional[str],events: List[types.Event],objects: List[str],
        baml_options: BamlCallOptions = {},
    ) -> List[types.ObjectInvolvement]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractObjectInvolvements",
        {
          "scene_text": scene_text,"story_context": story_context,"events": events,"objects": objects,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.ObjectInvolvement], raw.cast_to(types, types))
    
    def ExtractObjects(
        self,
        scene_text: str,story_context: Optional[str],known_object_uuids: List[str],
        baml_options: BamlCallOptions = {},
    ) -> List[types.Object]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractObjects",
        {
          "scene_text": scene_text,"story_context": story_context,"known_object_uuids": known_object_uuids,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.Object], raw.cast_to(types, types))
    
    def ExtractOrganizations(
        self,
        scene_text: str,story_context: Optional[str],known_agents: List[types.Agent],
        baml_options: BamlCallOptions = {},
    ) -> List[types.Organization]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractOrganizations",
        {
          "scene_text": scene_text,"story_context": story_context,"known_agents": known_agents,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.Organization], raw.cast_to(types, types))
    
    def ExtractRatings(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Ratings:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractRatings",
        {
          "text": text,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.Ratings, raw.cast_to(types, types))
    
    def ExtractResume(
        self,
        resume: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractResume",
        {
          "resume": resume,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.Resume, raw.cast_to(types, types))
    
    def ExtractScene(
        self,
        scene_text: str,story_context: Optional[str],
        baml_options: BamlCallOptions = {},
    ) -> types.OntoMediaScene:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractScene",
        {
          "scene_text": scene_text,"story_context": story_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.OntoMediaScene, raw.cast_to(types, types))
    
    def ExtractSceneMetadata(
        self,
        scene_text: str,story_context: Optional[str],
        baml_options: BamlCallOptions = {},
    ) -> types.SceneMetadata:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractSceneMetadata",
        {
          "scene_text": scene_text,"story_context": story_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.SceneMetadata, raw.cast_to(types, types))
    
    def ExtractStoryMetadata(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.StoryMetadata:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractStoryMetadata",
        {
          "text": text,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.StoryMetadata, raw.cast_to(types, types))
    
    def ExtractStoryNotes(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.StoryNotes:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractStoryNotes",
        {
          "text": text,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.StoryNotes, raw.cast_to(types, types))
    
    def ExtractWorldbuilding(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Worldbuilding:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ExtractWorldbuilding",
        {
          "text": text,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.Worldbuilding, raw.cast_to(types, types))
    
    def InferObjectOwner(
        self,
        scene_text: str,object_uuid: str,agent_uuids: List[str],
        baml_options: BamlCallOptions = {},
    ) -> Optional[types.Agent]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "InferObjectOwner",
        {
          "scene_text": scene_text,"object_uuid": object_uuid,"agent_uuids": agent_uuids,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(Optional[types.Agent], raw.cast_to(types, types))
    
    def ResolveAgentCluster(
        self,
        entities: List[types.Agent],
        baml_options: BamlCallOptions = {},
    ) -> List[types.ResolvedAgent]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ResolveAgentCluster",
        {
          "entities": entities,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.ResolvedAgent], raw.cast_to(types, types))
    
    def ResolveLocationCluster(
        self,
        entities: List[types.Location],
        baml_options: BamlCallOptions = {},
    ) -> List[types.ResolvedLocation]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ResolveLocationCluster",
        {
          "entities": entities,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.ResolvedLocation], raw.cast_to(types, types))
    
    def ResolveObjectCluster(
        self,
        entities: List[types.Object],
        baml_options: BamlCallOptions = {},
    ) -> List[types.ResolvedObject]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ResolveObjectCluster",
        {
          "entities": entities,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.ResolvedObject], raw.cast_to(types, types))
    
    def ResolveOrganizationCluster(
        self,
        entities: List[types.Organization],
        baml_options: BamlCallOptions = {},
    ) -> List[types.ResolvedOrganization]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ResolveOrganizationCluster",
        {
          "entities": entities,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.ResolvedOrganization], raw.cast_to(types, types))
    
    def ResolveSceneAgents(
        self,
        scene_text: str,potential_agents: List[str],
        baml_options: BamlCallOptions = {},
    ) -> List[types.ResolvedAgent]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "ResolveSceneAgents",
        {
          "scene_text": scene_text,"potential_agents": potential_agents,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.ResolvedAgent], raw.cast_to(types, types))
    



class BamlStreamClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    def ExtractAgentParticipations(
        self,
        scene_text: str,story_context: Optional[str],events: List[types.Event],agents: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[List[partial_types.AgentParticipation], List[types.AgentParticipation]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractAgentParticipations",
        {
          "scene_text": scene_text,
          "story_context": story_context,
          "events": events,
          "agents": agents,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[List[partial_types.AgentParticipation], List[types.AgentParticipation]](
        raw,
        lambda x: cast(List[partial_types.AgentParticipation], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.AgentParticipation], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractAgents(
        self,
        scene_text: str,story_context: Optional[str],known_agents: List[types.Agent],agent_name_to_uuid_mapping: Dict[str, str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[List[partial_types.Agent], List[types.Agent]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractAgents",
        {
          "scene_text": scene_text,
          "story_context": story_context,
          "known_agents": known_agents,
          "agent_name_to_uuid_mapping": agent_name_to_uuid_mapping,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[List[partial_types.Agent], List[types.Agent]](
        raw,
        lambda x: cast(List[partial_types.Agent], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.Agent], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractAllWikiData(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.WikiData, types.WikiData]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractAllWikiData",
        {
          "text": text,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.WikiData, types.WikiData](
        raw,
        lambda x: cast(partial_types.WikiData, x.cast_to(types, partial_types)),
        lambda x: cast(types.WikiData, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractCastCrew(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.CastCrew, types.CastCrew]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractCastCrew",
        {
          "text": text,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.CastCrew, types.CastCrew](
        raw,
        lambda x: cast(partial_types.CastCrew, x.cast_to(types, partial_types)),
        lambda x: cast(types.CastCrew, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractContinuity(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Continuity, types.Continuity]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractContinuity",
        {
          "text": text,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.Continuity, types.Continuity](
        raw,
        lambda x: cast(partial_types.Continuity, x.cast_to(types, partial_types)),
        lambda x: cast(types.Continuity, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractEntities(
        self,
        scene_text: str,story_context: Optional[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.OntoMediaEntities, types.OntoMediaEntities]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractEntities",
        {
          "scene_text": scene_text,
          "story_context": story_context,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.OntoMediaEntities, types.OntoMediaEntities](
        raw,
        lambda x: cast(partial_types.OntoMediaEntities, x.cast_to(types, partial_types)),
        lambda x: cast(types.OntoMediaEntities, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractEpisodePlot(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[List[partial_types.EpisodePlot], List[types.EpisodePlot]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractEpisodePlot",
        {
          "text": text,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[List[partial_types.EpisodePlot], List[types.EpisodePlot]](
        raw,
        lambda x: cast(List[partial_types.EpisodePlot], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.EpisodePlot], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractEvents(
        self,
        scene_text: str,story_context: Optional[str],scene_number: int,known_agents: List[str],known_objects: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[List[partial_types.Event], List[types.Event]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractEvents",
        {
          "scene_text": scene_text,
          "story_context": story_context,
          "scene_number": scene_number,
          "known_agents": known_agents,
          "known_objects": known_objects,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[List[partial_types.Event], List[types.Event]](
        raw,
        lambda x: cast(List[partial_types.Event], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.Event], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractHomeMedia(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.HomeRelease, types.HomeRelease]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractHomeMedia",
        {
          "text": text,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.HomeRelease, types.HomeRelease](
        raw,
        lambda x: cast(partial_types.HomeRelease, x.cast_to(types, partial_types)),
        lambda x: cast(types.HomeRelease, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractLocations(
        self,
        scene_text: str,story_context: Optional[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[List[partial_types.Location], List[types.Location]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractLocations",
        {
          "scene_text": scene_text,
          "story_context": story_context,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[List[partial_types.Location], List[types.Location]](
        raw,
        lambda x: cast(List[partial_types.Location], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.Location], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractObjectInvolvements(
        self,
        scene_text: str,story_context: Optional[str],events: List[types.Event],objects: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[List[partial_types.ObjectInvolvement], List[types.ObjectInvolvement]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractObjectInvolvements",
        {
          "scene_text": scene_text,
          "story_context": story_context,
          "events": events,
          "objects": objects,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[List[partial_types.ObjectInvolvement], List[types.ObjectInvolvement]](
        raw,
        lambda x: cast(List[partial_types.ObjectInvolvement], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.ObjectInvolvement], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractObjects(
        self,
        scene_text: str,story_context: Optional[str],known_object_uuids: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[List[partial_types.Object], List[types.Object]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractObjects",
        {
          "scene_text": scene_text,
          "story_context": story_context,
          "known_object_uuids": known_object_uuids,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[List[partial_types.Object], List[types.Object]](
        raw,
        lambda x: cast(List[partial_types.Object], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.Object], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractOrganizations(
        self,
        scene_text: str,story_context: Optional[str],known_agents: List[types.Agent],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[List[partial_types.Organization], List[types.Organization]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractOrganizations",
        {
          "scene_text": scene_text,
          "story_context": story_context,
          "known_agents": known_agents,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[List[partial_types.Organization], List[types.Organization]](
        raw,
        lambda x: cast(List[partial_types.Organization], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.Organization], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractRatings(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Ratings, types.Ratings]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractRatings",
        {
          "text": text,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.Ratings, types.Ratings](
        raw,
        lambda x: cast(partial_types.Ratings, x.cast_to(types, partial_types)),
        lambda x: cast(types.Ratings, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractResume(
        self,
        resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Resume, types.Resume]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractResume",
        {
          "resume": resume,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.Resume, types.Resume](
        raw,
        lambda x: cast(partial_types.Resume, x.cast_to(types, partial_types)),
        lambda x: cast(types.Resume, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractScene(
        self,
        scene_text: str,story_context: Optional[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.OntoMediaScene, types.OntoMediaScene]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractScene",
        {
          "scene_text": scene_text,
          "story_context": story_context,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.OntoMediaScene, types.OntoMediaScene](
        raw,
        lambda x: cast(partial_types.OntoMediaScene, x.cast_to(types, partial_types)),
        lambda x: cast(types.OntoMediaScene, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractSceneMetadata(
        self,
        scene_text: str,story_context: Optional[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.SceneMetadata, types.SceneMetadata]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractSceneMetadata",
        {
          "scene_text": scene_text,
          "story_context": story_context,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.SceneMetadata, types.SceneMetadata](
        raw,
        lambda x: cast(partial_types.SceneMetadata, x.cast_to(types, partial_types)),
        lambda x: cast(types.SceneMetadata, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractStoryMetadata(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.StoryMetadata, types.StoryMetadata]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractStoryMetadata",
        {
          "text": text,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.StoryMetadata, types.StoryMetadata](
        raw,
        lambda x: cast(partial_types.StoryMetadata, x.cast_to(types, partial_types)),
        lambda x: cast(types.StoryMetadata, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractStoryNotes(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.StoryNotes, types.StoryNotes]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractStoryNotes",
        {
          "text": text,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.StoryNotes, types.StoryNotes](
        raw,
        lambda x: cast(partial_types.StoryNotes, x.cast_to(types, partial_types)),
        lambda x: cast(types.StoryNotes, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractWorldbuilding(
        self,
        text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Worldbuilding, types.Worldbuilding]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ExtractWorldbuilding",
        {
          "text": text,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.Worldbuilding, types.Worldbuilding](
        raw,
        lambda x: cast(partial_types.Worldbuilding, x.cast_to(types, partial_types)),
        lambda x: cast(types.Worldbuilding, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def InferObjectOwner(
        self,
        scene_text: str,object_uuid: str,agent_uuids: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.Agent, Optional[types.Agent]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "InferObjectOwner",
        {
          "scene_text": scene_text,
          "object_uuid": object_uuid,
          "agent_uuids": agent_uuids,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.Agent, Optional[types.Agent]](
        raw,
        lambda x: cast(partial_types.Agent, x.cast_to(types, partial_types)),
        lambda x: cast(Optional[types.Agent], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ResolveAgentCluster(
        self,
        entities: List[types.Agent],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[List[partial_types.ResolvedAgent], List[types.ResolvedAgent]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ResolveAgentCluster",
        {
          "entities": entities,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[List[partial_types.ResolvedAgent], List[types.ResolvedAgent]](
        raw,
        lambda x: cast(List[partial_types.ResolvedAgent], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.ResolvedAgent], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ResolveLocationCluster(
        self,
        entities: List[types.Location],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[List[partial_types.ResolvedLocation], List[types.ResolvedLocation]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ResolveLocationCluster",
        {
          "entities": entities,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[List[partial_types.ResolvedLocation], List[types.ResolvedLocation]](
        raw,
        lambda x: cast(List[partial_types.ResolvedLocation], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.ResolvedLocation], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ResolveObjectCluster(
        self,
        entities: List[types.Object],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[List[partial_types.ResolvedObject], List[types.ResolvedObject]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ResolveObjectCluster",
        {
          "entities": entities,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[List[partial_types.ResolvedObject], List[types.ResolvedObject]](
        raw,
        lambda x: cast(List[partial_types.ResolvedObject], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.ResolvedObject], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ResolveOrganizationCluster(
        self,
        entities: List[types.Organization],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[List[partial_types.ResolvedOrganization], List[types.ResolvedOrganization]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ResolveOrganizationCluster",
        {
          "entities": entities,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[List[partial_types.ResolvedOrganization], List[types.ResolvedOrganization]](
        raw,
        lambda x: cast(List[partial_types.ResolvedOrganization], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.ResolvedOrganization], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ResolveSceneAgents(
        self,
        scene_text: str,potential_agents: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[List[partial_types.ResolvedAgent], List[types.ResolvedAgent]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "ResolveSceneAgents",
        {
          "scene_text": scene_text,
          "potential_agents": potential_agents,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[List[partial_types.ResolvedAgent], List[types.ResolvedAgent]](
        raw,
        lambda x: cast(List[partial_types.ResolvedAgent], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.ResolvedAgent], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    

b = BamlSyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)

__all__ = ["b"]